package:
  name: htseq
  version: "0.11.4"

source:
  url: https://files.pythonhosted.org/packages/ec/f9/fcbc93aef266466973e997db67e13e083a9dd44e722ca703a80cfe6d46d4/HTSeq-0.11.4.tar.gz
  sha256: f0e0efd646567ff836d8634fa0800ec2632e17db0b288dc38e0a05b63d1896d9

build:
  number: 0
  script: "{PYTHON} -m pip install . --ignore-installed --no-deps -vv"

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - python
    - setuptools
    - cython
    - numpy
    - pysam >=0.9.0
    - swig >=3.0.8

  run:
    - python
    - {{ pin_compatible('numpy') }}
    - matplotlib-base >=1.4
    - pysam >=0.9.0

test:
  # Python imports
  imports:
    - HTSeq._HTSeq_internal
    - HTSeq.StepVector
    - HTSeq._version
    - HTSeq.scripts.count
    - HTSeq.scripts.qa

  commands:
    - htseq-count -h
    - htseq-qa -h

about:
  home: https://github.com/simon-anders/htseq
  license: GPL-3.0
  summary: 'HTSeq is a Python library to facilitate processing and analysis of data from high-throughput sequencing (HTS) experiments.'

extra:
  identifiers:
    - biotools:htseq
    - doi:10.1093/bioinformatics/btu638
